{{- if .Values.aiService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aicmp-platform.fullname" . }}-ai-service
  labels:
    {{- include "aicmp-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: "ai-service"
spec:
  replicas: {{ .Values.aiService.replicaCount }}
  selector:
    matchLabels:
      {{- include "aicmp-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "ai-service"
  template:
    metadata:
      labels:
        {{- include "aicmp-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "ai-service"
      annotations:
        {{- include "aicmp-platform.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aicmp-platform.fullname" . }}-ai-service
      securityContext:
        {{- toYaml .Values.aiService.securityContext | nindent 8 }}
      containers:
      - name: ai-service
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.aiService.image.repository }}:{{ .Values.aiService.image.tag }}"
        imagePullPolicy: {{ .Values.aiService.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.aiService.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.aiService.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- end }}
          {{- if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.aiService.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.aiService.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.aiService.readinessProbe | nindent 10 }}
        volumeMounts:
        - name: ai-config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: ai-config
        configMap:
          name: {{ include "aicmp-platform.fullname" . }}-ai-service-config
{{- end }} 