{{- if and .Values.kubectlCost.enabled .Values.kubectlCost.security.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}-kubectl-cost
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "kubectl-cost"
spec:
  podSelector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "kubectl-cost"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- range .Values.kubectlCost.security.networkPolicies.ingress }}
    - from:
    {{- range .from }}
      {{- if .namespaceSelector }}
      - namespaceSelector:
          matchLabels:
      {{- range $key, $value := .namespaceSelector.matchLabels }}
            {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .podSelector }}
      - podSelector:
          matchLabels:
      {{- range $key, $value := .podSelector.matchLabels }}
            {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    {{- end }}
      ports:
    {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
    {{- end }}
  {{- end }}
  egress:
  {{- range .Values.kubectlCost.security.networkPolicies.egress }}
    - to:
    {{- range .to }}
      {{- if .namespaceSelector }}
      - namespaceSelector:
          matchLabels:
      {{- range $key, $value := .namespaceSelector.matchLabels }}
            {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .podSelector }}
      - podSelector:
          matchLabels:
      {{- range $key, $value := .podSelector.matchLabels }}
            {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    {{- end }}
      ports:
    {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }} 