{{- if .Values.kubectlCost.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-kubectl-cost
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "kubectl-cost"
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubectlCost.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "kubectl-cost"
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "kubectl-cost"
      annotations:
        {{- include "common.annotations" . | nindent 8 }}
    spec:
      {{- if .Values.kubectlCost.serviceAccount.create }}
      serviceAccountName: {{ .Values.kubectlCost.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.kubectlCost.deployment.podSecurityContext | nindent 8 }}
      containers:
      - name: kubectl-cost
        image: "{{ .Values.kubectlCost.deployment.image.repository }}:{{ .Values.kubectlCost.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.kubectlCost.deployment.image.pullPolicy }}
        args:
        - "server"
        - "--kubecost-api-url={{ .Values.kubectlCost.config.kubecostAPI.url }}"
        - "--port={{ .Values.kubectlCost.service.port }}"
        - "--timeout={{ .Values.kubectlCost.config.kubecostAPI.timeout }}"
        - "--allocation-window={{ .Values.kubectlCost.config.allocation.window }}"
        - "--aggregate={{ .Values.kubectlCost.config.allocation.aggregate }}"
        {{- if .Values.kubectlCost.config.allocation.idle }}
        - "--include-idle"
        {{- end }}
        {{- if .Values.kubectlCost.config.allocation.shared }}
        - "--include-shared"
        {{- end }}
        {{- if .Values.kubectlCost.optimization.enabled }}
        - "--enable-optimization"
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.kubectlCost.service.port }}
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
        env:
        - name: KUBECOST_API_URL
          value: {{ .Values.kubectlCost.config.kubecostAPI.url | quote }}
        - name: KUBECOST_API_PORT
          value: {{ .Values.kubectlCost.config.kubecostAPI.port | quote }}
        - name: ALLOCATION_WINDOW
          value: {{ .Values.kubectlCost.config.allocation.window | quote }}
        - name: AGGREGATE_LEVEL
          value: {{ .Values.kubectlCost.config.allocation.aggregate | quote }}
        - name: OPTIMIZATION_ENABLED
          value: {{ .Values.kubectlCost.optimization.enabled | quote }}
        - name: RECOMMENDATIONS_ENABLED
          value: {{ .Values.kubectlCost.optimization.recommendations | quote }}
        - name: ALERTS_ENABLED
          value: {{ .Values.kubectlCost.optimization.alerts | quote }}
        - name: CPU_THRESHOLD
          value: {{ .Values.kubectlCost.optimization.thresholds.cpu | quote }}
        - name: MEMORY_THRESHOLD
          value: {{ .Values.kubectlCost.optimization.thresholds.memory | quote }}
        - name: COST_THRESHOLD
          value: {{ .Values.kubectlCost.optimization.thresholds.cost | quote }}
        resources:
          {{- toYaml .Values.kubectlCost.deployment.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.kubectlCost.deployment.securityContext | nindent 10 }}
        volumeMounts:
        - name: reports
          mountPath: /reports
        - name: config
          mountPath: /etc/kubectl-cost
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: reports
        persistentVolumeClaim:
          claimName: {{ include "common.fullname" . }}-kubectl-cost-reports
      - name: config
        configMap:
          name: {{ include "common.fullname" . }}-kubectl-cost-config
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
{{- end }} 