{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitors }}
{{- range .Values.monitoring.serviceMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "monitoring"
spec:
  selector:
    {{- toYaml .selector | nindent 4 }}
  endpoints:
    {{- toYaml .endpoints | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
{{- end }} 