{{- if .Values.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-database-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.database.username | b64enc }}
  password: {{ .Values.secrets.database.password | b64enc }}
  url: {{ .Values.secrets.database.url | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-redis-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.secrets.redis.url | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-jwt-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.secrets.jwt.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-aws-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.secrets.aws.accessKeyId | b64enc }}
  secret-access-key: {{ .Values.secrets.aws.secretAccessKey | b64enc }}
{{- end }} 